# Generated by Django 5.2.4 on 2025-09-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_especie_alter_pet_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Ração', max_length=100)),
                ('quantidade', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.TimeField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.pet')),
            ],
        ),
    ]
